### ISSUE TITLE
AttributeError: 'MultiTaskTrainingArguments' object has no attribute 'uniform_mt_sampling'

### ISSUE THREAD

**Issue by heatxg** [CAMTL/CA-MTL#2]
It looks like there are arguments (`percent_of_max_data_size` & `uniform_mt_sampling`) missing that are consumed by the `MultiTaskTrainer` for the `__len__` method.   
https://github.com/CAMTL/CA-MTL/blob/f994a44e0921674501083edb9eeccda74e93497e/src/mtl_trainer.py#L162

  
This is causing errors in some of the super methods.   
https://github.com/huggingface/transformers/blob/b42586ea560a20dcadb78472a6b4596f579e9043/src/transformers/trainer.py#L367     
  

I've traced them through the repo but found only this reference and do not see them listed in the cl args.   
  
How would you suggest mitigating?

**Comment by CAMTL** [comment]
@heatxg  Thank you for bringing this to us. I'm taking a look

**Comment by Am1n3e** [comment]
@heatxg  I have make a fix in this branch **Am1n3e-bugfix-add-missing-args**. However, I don't have the time to test it. 
Can you give a try and let me know if that fixes your issue ?

**Comment by heatxg** [comment]
@Am1n3e Thank you for taking the time to look into this. I will give the fix a test this evening and update you.

**Comment by heatxg** [comment]
@Am1n3e This got us past the original missing args but now we are stuck at another missing arg https://github.com/CAMTL/CA-MTL/blob/5556f8d83bb5760f4cbb701a78bfcf2f93cc6398/src/mtl_trainer.py#L181

**Comment by CAMTL** [comment]
@heatxg Thank for getting back to me. I will check it and come back to you!

**Comment by Am1n3e** [comment]
@heatxg I will take a look at the issue this week (I was a bit busy).

**Comment by jpilaul** [comment]
This issue is fixed in https://github.com/CAMTL/CA-MTL/pull/3
