### ISSUE TITLE
frozen parameters

### ISSUE THREAD

**Issue by PingYu-iris** [CAMTL/CA-MTL#6]
In your paper, you mentioned that this model frozen parameters in the 1-6 layers. However, in your code, the parameters in first six layers implemented by `BertLayer9` seems not been frozen.

**Comment by Am1n3e** [comment]
Hello @PingYu-iris, we are working making the layer freezing code available. 
We will notify you in this PR once it is merged.

Thanks!

**Comment by jpilaul** [comment]
PR is here: https://github.com/CAMTL/CA-MTL/pull/7
